# Generated by Django 3.0.6 on 2020-05-24 03:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0004_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
