# Generated by Django 3.0.8 on 2020-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0005_auto_20200524_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
