# Generated by Django 3.0.8 on 2020-07-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0006_auto_20200719_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='actor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
